export const ADD_VISITED_POST = 'user:ADD_VISITED_POST';
export const GET_VISITED_POSTS = 'user:GET_VISITED_POSTS';

export const REQUEST_RECOMMENDED_POSTS = 'user:REQUEST_RECOMMENDED_POSTS';
export const RECEIVE_RECOMMENDED_POSTS = 'user:RECEIVE_RECOMMENDED_POSTS';

export const TOP_INSTAGRAM_CLICK = 'user:TOP_INSTAGRAM_CLICK';
export const NOTIFYBOX_INSTAGRAM_CLICK = 'user:NOTIFYBOX_INSTAGRAM_CLICK';
export const NOTIFYBOX_NOTIFY_CLICK = 'user:NOTIFYBOX_INSTAGRAM_CLICK';
export const LINKEDIN_BOTTOM_CLICK = 'user:LINKEDIN_BOTTOM_CLICK';
export const INSTAGRAM_BOTTOM_CLICK = 'user:INSTAGRAM_BOTTOM_CLICK';
export const GITHUB_BOTTOM_CLICK = 'user:GITHUB_BOTTOM_CLICK';
