export const ADD_VISITED_POST = 'user:ADD_VISITED_POST';
export const GET_VISITED_POSTS = 'user:GET_VISITED_POSTS';

export const REQUEST_RECOMMENDED_POSTS = 'user:REQUEST_RECOMMENDED_POSTS';
export const RECEIVE_RECOMMENDED_POSTS = 'user:RECEIVE_RECOMMENDED_POSTS';
