export const REQUEST_POSTS = 'posts:REQUEST_POSTS';
export const RECEIVE_POSTS = 'posts:RECEIVE_POSTS';

export const REQUEST_SINGLE_POST = 'post:REQUEST_SINGLE_POST';
export const RECEIVE_SINGLE_POST = 'post:RECEIVE_SINGLE_POST';
export const SET_CURRENT_POST = 'post:SET_CURRENT_POST';
export const SET_ACTIVE_POST = 'post:SET_ACTIVE_POST';

export const REQUEST_POSTS_LINKS = 'posts:REQUEST_POSTS_LINKS';
export const RECEIVE_POSTS_LINKS = 'posts:RECEIVE_POSTS_LINKS';

export const SET_RECOMMENDED_POSTS = 'posts:SET_RECOMMENDED_POSTS';
